### ISSUE TITLE
Delete images

### ISSUE THREAD

**Issue by mariahcarey** [tomlandia/fuckr#56] opened 2016-07-02 10:09 UTC
'Send image' function is awesome but I can't find a way to delete any (duplicates, etc)? I've looked for the storage file mentioned in another thread but can't find it. Possibly because I'm on a mac? Problem persists even after I delete & redownload the program.

**Comment by tomlandia** [comment] 2016-08-10 09:46
Duplicate of #27.

**Closed by tomlandia** 2016-08-10 09:46 UTC
